// saga types
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const HOTELS_REQUEST = 'HOTELS_REQUEST';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
export const SORT_FAVOURITES = 'SORT_FAVOURITES';

// redux types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const HOTELS_SUCCESS = 'HOTELS_SUCCESS';
export const ADD_TO_FAVOURITES_SUCCESS = 'ADD_TO_FAVOURITES_SUCCESS';
export const REMOVE_FROM_FAVOURITES_SUCCESS = 'REMOVE_FROM_FAVOURITES_SUCCESS';
export const SORT_FAVOURITES_SUCCESS = 'SORT_FAVOURITES_SUCCESS';

export const RATING_HIGH = 'RATING_HIGH';
export const RATING_LOW = 'RATING_LOW';
export const PRICE_HIGH = 'PRICE_HIGH';
export const PRICE_LOW = 'PRICE_LOW';