export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const LOGIN_ACTION = 'LOGIN_ACTION';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';

export const HOTELS_REQUEST = 'HOTELS_REQUEST';
export const HOTELS_ACTION = 'HOTELS_ACTION';

export const ADD_TO_FAVOURITES_REQUEST = 'ADD_TO_FAVOURITES_REQUEST';
export const ADD_TO_FAVOURITES_ACTION = 'ADD_TO_FAVOURITES_ACTION';

export const REMOVE_FROM_FAVOURITES_REQUEST = 'REMOVE_FROM_FAVOURITES_REQUEST';
export const REMOVE_FROM_FAVOURITES_ACTION = 'REMOVE_FROM_FAVOURITES_ACTION';

// saga types
export const SORT_FAVOURITES = 'SORT_FAVOURITES';

// redux types
export const SORT_FAVOURITES_SUCCESS = 'SORT_FAVOURITES_SUCCESS';

export const RATING_HIGH = 'RATING_HIGH';
export const RATING_LOW = 'RATING_LOW';
export const PRICE_HIGH = 'PRICE_HIGH';
export const PRICE_LOW = 'PRICE_LOW';